config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :tweets do
    member do
      get :star
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
root 'tweets#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/star.rb
class Star < ApplicationRecord
  belongs_to :tweet
  belongs_to :user
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  has_many :stars

  validates :text, presence: true, length: { maximum: 140 }, uniqueness: true
  validates :user_name, presence: true # long version  { :presence => true }

  def not_already_stared?(user)
    stars.where(user: user).count == 0  # user: user  ->   hash
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  # long form -> before_action :authenticate_user!, { :except => [:index] }
  # It is referring to the index action (method in the controller)
  # It's in hash form Because we can list multiple actions to exclude
  # GET /tweets
  def index
    @tweets = Tweet.all.order("created_at DESC").where("text LIKE ?", "%#{params[:search]}%")
  end

  # GET /tweets/1
  def show
    @tweet = Tweet.find(params[:id])
  end

  # GET /tweets/new
  def new
    @tweet = Tweet.new
  end

  # GET /tweets/1/edit
  def edit
    @tweet = Tweet.find(params[:id])
  end

  # POST /tweets
  def create
    @tweet = Tweet.new(tweet_params)
    # @tweet.email = current_user.email

    if @tweet.save
      redirect_to @tweet, notice: 'Tweet was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /tweets/1
  def update
    @tweet = Tweet.find(params[:id])
    if @tweet.update(tweet_params)
      redirect_to @tweet, notice: 'Tweet was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /tweets/1
  def destroy
    @tweet = Tweet.find(params[:id])
    @tweet.destroy
    redirect_to tweets_url, notice: 'Tweet was successfully destroyed.'
  end

  # upstar
  def star
    @tweet = Tweet.find(params[:id])
    if @tweet.not_already_stared?(current_user)
      # if @tweet.stars.where(user: current_user, upstar: true).count == 0 # ref video 31:00 / 43:00
      @tweet.stars.create(user: current_user)
      redirect_to tweets_path
    else
      redirect_to tweets_path, notice: "You've already starred"
    end
  end

  private
    # Only allow a trusted parameter "white list" through.
    def tweet_params
      params.require(:tweet).permit(:text, :user_name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{charset: "utf-8"}
    %meta{content: "IE=edge", "http-equiv" => "X-UA-Compatible"}
    %meta{content: "width=device-width, initial-scale=1", name: "viewport"}
    %meta{content: "", name: "description"}
    %meta{content: "", name: "author"}
    %title
      = Minitwitter

    / HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries
    /[if lt IE 9]
      = javascript_include_tag "https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js", "https://oss.maxcdn.com/respond/1.4.2/respond.min.js"

    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    %nav.navbar.navbar-inverse.navbar-fixed-top{role: "navigation"}
      .container
        .navbar-header
          %button.navbar-toggle.collapsed{type: "button", data: {toggle: "collapse", target: "#navbar"}, aria: {expanded: "false", controls: "navbar"} }
            %span.sr-only Toggle navigation
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          = link_to "#", class: "navbar-brand, birdlogo" do
            = image_tag("twit.png", size: "90x90")

        #navbar.collapse.navbar-collapse
          %ul.nav.navbar-nav.listbody
            %li.active
              = link_to "Home", root_path
            %li
              = link_to new_tweet_path do
                New Tweet

          %ul.nav.navbar-nav.navbar-right
            %li
              %form.navbar-form.navbar-right{action: tweets_path}
                .form-group
                  %input.form-control.search-tweets{placeholder: "Search", type: "text"}/
                  %button.btn.btn-default.search-button{type: "submit"} Search
            - if user_signed_in?
              %li
                %p.navbar-text
                  = current_user.email
              %li
                - if user_signed_in?
                  = link_to "LogOut", destroy_user_session_path, method: :delete
                - else
                  = link_to "LogIn", new_user_session_path
    .container.listpadding
      - flash.each do |name, msg|
        = content_tag :div, class: "alert alert-#{name == :error ? "danger" : "success" } alert-dismissable", role: "alert" do
          %button.close{type: "button", data: {dismiss: "alert"} }
            %span{aria: {hidden: "true"} } &times;
            %span.sr-only Close
          = msg
      = yield

app/views/tweets/_form.html.haml
= form_for @tweet, html: { class: "form-horizontal", role: "form" } do |f|
  -if @tweet.errors.any?
    .alert.alert-danger.alert-dismissable{role: "alert"}
      %button.close{type: "button", data: {dismiss: "alert"} }
        %span{aria: {hidden: "true"} } &times;
        %span.sr-only Close
      %h4= "#{pluralize(@tweet.errors.count, "error")} prohibited this tweet from being saved:"

      %ul
        - @tweet.errors.full_messages.each do |msg|
          %li= msg

  .form-group
    = f.label :text, class: 'col-sm-2 control-label'
    .col-sm-10
      = f.text_field :text, class: 'form-control'
  .form-group
    = f.label :user_name, class: 'col-sm-2 control-label'
    .col-sm-10
      = f.text_field :user_name, class: 'form-control'
  .form-group
    .col-sm-offset-2.col-sm-10
      = f.submit class: 'btn btn-primary'

app/views/tweets/_tweet.html.haml
%tr
  %td
    %p
      = tweet.user_name
      ·
      = distance_of_time_in_words_to_now(tweet.created_at)
    %p
      - if tweet.text.include?("https")||tweet.text.include?("http")
        = link_to tweet.text, tweet.text
      - else
        = tweet.text
    %p
      = link_to star_tweet_path(tweet) do
        %span.star
      = tweet.stars.count

app/views/tweets/edit.html.haml
.page-header
  = link_to tweets_path, class: 'btn btn-default' do
    %span.glyphicon.glyphicon-list-alt
    Back
  = link_to @tweet, class: 'btn btn-primary' do
    %span.glyphicon.glyphicon-info-sign
    Show
  %h1 Editing tweet

= render 'form'

app/views/tweets/index.html.haml
.btn.btn-primary.toggle-star
  Toggle Stars
.table-responsive
  %table.table.table-striped.table-bordered.table-hover
    %tbody.search-results
      = render @tweets

app/views/tweets/index.js.erb
$('.search-results').html('<%= j(render @tweets) %>')

app/views/tweets/new.html.haml
.page-header
  = link_to tweets_path, class: 'btn btn-default' do
    %span.glyphicon.glyphicon-list-alt
    Back
  %h1 New tweet

= render 'form'

app/views/tweets/show.html.haml
.page-header
  = link_to tweets_path, class: 'btn btn-default' do
    %span.glyphicon.glyphicon-list-alt
    Back
  = link_to edit_tweet_path(@tweet), class: 'btn btn-primary' do
    %span.glyphicon.glyphicon-pencil
    Edit
  %h1 Show tweet

%dl.dl-horizontal
  %dt Text:
  %dd= @tweet.text
  %dt User name:
  %dd= @tweet.user_name